name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t act-three-image .

      - name: Push Docker Image
        run: |
          docker tag act-three-image:latest docker.pkg.github.com/${{ github.repository }}/act-three-image:latest
          docker push docker.pkg.github.com/${{ github.repository }}/act-three-image:latest
